#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(647, 157)
        self.message = QtWidgets.QLabel(parent=Dialog)
        self.message.setGeometry(QtCore.QRect(4, 5, 641, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.message.setFont(font)
        self.message.setText("")
        self.message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.message.setObjectName("message")
        self.confirm_btn = QtWidgets.QPushButton(parent=Dialog)
        self.confirm_btn.setGeometry(QtCore.QRect(480, 100, 141, 41))
        self.confirm_btn.setStyleSheet("border: 2px solid black;\n"
"border-radius: 5px")
        self.confirm_btn.setObjectName("confirm_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Внимание"))
        self.confirm_btn.setText(_translate("Dialog", "Понятно"))
